# fly.toml app configuration file generated for cherwood-backend-cold-river-1843-quiet-breeze-3861 on 2024-02-08T20:30:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cherwood-backend-cold-river-1843-quiet-breeze-3861'
primary_region = 'waw'
console_command = '/code/manage.py shell'
SESSION_DRIVER = "cookie"

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[processes]
  app = "python -m gunicorn --bind :8000 --workers 2 cherwood_shop.wsgi"
  worker = "celery -A cherwood_shop worker -l info"
  beat = "celery -A cherwood_shop beat -l info"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
