# Generated by Django 4.2.9 on 2024-02-08 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_city_user_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tel_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$",
                        message="Make sure your phone number consists of 10 digits",
                    )
                ],
            ),
        ),
    ]
